name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: Ruby ${{ matrix.ruby-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby-version: ['2.5', '2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Ruby 2.5 needs a newer RubyGems to support frozen-string-literal
      if: ${{ matrix.ruby-version == '2.5' }}
      run: gem update --system 2.7.11
    - name: Install dependencies
      run: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
    - name: Run tests
      run: bundle exec rake
      env:
        RUBYOPT: --enable-frozen-string-literal
